security:

    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Mygento\Application\Security\User\IdentityUser:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Mygento\Application\Security\User\IdentityUser
                property: id

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Mygento\Application\Security\UserAuthenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
         - { path: ^/login, roles: PUBLIC_ACCESS }
         - { path: ^/, roles: ROLE_USER }
